server_url: localhost:8000
ssh_url: localhost:2222
tunnel_url: localhost:8001
secret_key: Zq5Zk5gP5qHGg28nixeqRIOMM9Zo3EUgWnFAEnJnwC
use_localhost: true
debug: true
use_vite: true
tunnels:
  - name: portr
    subdomain: portr
    port: 4321
    type: tcp
