// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type Connection struct {
	ID           int64
	Subdomain    string
	TeamMemberID int64
	CreatedAt    time.Time
	ClosedAt     interface{}
}

type GlobalSetting struct {
	ID                      int64
	UserInviteEmailSubject  interface{}
	UserInviteEmailTemplate interface{}
}

type Invite struct {
	ID                    int64
	Email                 string
	Role                  string
	Status                string
	InvitedByTeamMemberID int64
	TeamID                int64
	CreatedAt             time.Time
}

type Session struct {
	ID        int64
	UserID    int64
	Token     string
	CreatedAt time.Time
}

type Team struct {
	ID        int64
	Name      string
	Slug      string
	CreatedAt time.Time
}

type TeamMember struct {
	ID        int64
	UserID    int64
	TeamID    int64
	SecretKey string
	Role      string
	CreatedAt time.Time
}

type User struct {
	ID                int64
	Email             string
	FirstName         interface{}
	LastName          interface{}
	IsSuperUser       bool
	GithubAccessToken interface{}
	GithubAvatarUrl   interface{}
	CreatedAt         time.Time
}
