context:
  pkg_name: ${{ env.get("PKG_NAME", default="portr")}}
  pkg_version: ${{ env.get("PKG_VERSION", default="0.0.1") }}

package:
  name: ${{ pkg_name|lower }}
  version: ${{ pkg_version }}

source:
  - path: ..
    use_gitignore: false

build:
  number: 0
  script:
    - PKG_NAME="${{ pkg_name }}" bash ./build.sh

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - pnpm
    - nodejs
