name: Publish to prefix.dev

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    if: vars.DISABLE_PORTR_PUBLISH != 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-64
          - os: macos-latest
            target: osx-64
          - os: macos-latest
            target: osx-arm64
          - os: windows-latest
            target: win-64

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Variables
        shell: bash
        run: |
          echo "PKG_NAME=portr" >> $GITHUB_ENV
          echo "PKG_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          artifact-name: portr-${{ matrix.target }}
          build-args: --target-platform ${{ matrix.target }}

      - run: |
          for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \)); do
            echo "Uploading ${pkg}"
            rattler-build upload prefix -c ${{ github.repository_owner }} "${pkg}"
          done
