name: Portr admin

on:
  push:
    branches: ["main"]
    paths:
      - "admin/**"
      - ".github/workflows/portr-admin.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "admin/**"
      - ".github/workflows/portr-admin.yml"

permissions:
  contents: read

env:
  PORTR_DOMAIN: localhost:8000
  PORTR_ADMIN_GITHUB_CLIENT_ID: ""
  PORTR_ADMIN_GITHUB_CLIENT_SECRET: ""
  PORTR_SERVER_URL: localhost:8000
  PORTR_SSH_URL: localhost:2222
  PORTR_ADMIN_USE_VITE: true
  PORTR_ADMIN_ENCRYPTION_KEY: "mj-qoeMhLQp_cHnMU9nsLfCMnNkZ6XBcFefy4VxzOe8="
  PORTR_DB_URL: ""

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./admin
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: admin/requirements*.lock
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sed '/-e/d' requirements.lock > requirements.txt && python -m pip install -r requirements.txt
          sed '/-e/d' requirements-dev.lock > requirements-dev.txt && python -m pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          pytest
