name: Publish to prefix.dev

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    if: vars.DISABLE_PORTR_PUBLISH != 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Highly recommended for matrix builds
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-64
            package: portr
          - os: ubuntu-latest
            target: linux-64
            package: portrd
          - os: macos-latest
            target: osx-64
            package: portr
          - os: macos-latest
            target: osx-64
            package: portrd
          - os: macos-latest
            target: osx-arm64
            package: portr
          - os: macos-latest
            target: osx-arm64
            package: portrd
          - os: windows-latest
            target: win-64
            package: portr
          - os: windows-latest
            target: win-64
            package: portrd

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Variables
        shell: bash
        run: |
          CLEAN_TAG=${GITHUB_REF_NAME#v}
          echo "STRIPPED_TAG=$CLEAN_TAG" >> $GITHUB_ENV

      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.34
        with:
          recipe-path: conda.recipe/recipe.yaml
          upload-artifact: true
          build-args: |
            --target-platform ${{ matrix.target }}
            --set pkg_name=${{ matrix.package }}
            --set version=${{ env.STRIPPED_TAG }}
