name: Publish packages

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tunnel

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Setup client
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
          run_install: false

      - name: Install client dependencies
        run: pnpm --dir internal/client/dashboard/ui install

      - name: Build client
        run: pnpm --dir internal/client/dashboard/ui build

      - name: Publish packages
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./admin/Dockerfile
            image: amalshaji/portr-admin
            context: ./admin
          - dockerfile: ./tunnel/Dockerfile
            image: amalshaji/portr-tunnel
            context: ./tunnel
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: amalshaji
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64
          file: ${{ matrix.dockerfile }}
          build-args: |
            VERSION=${{ github.ref_name }}
