name: Publish packages

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.22"
          cache: true
          cache-dependency-path: tunnel/go.sum

      - name: Publish packages
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Docker meta
#         id: meta
#         uses: docker/metadata-action@v4
#         with:
#           images: |
#             amalshaji/beaver
#           tags: |
#             type=semver,pattern={{version}}

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: amalshaji
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           platforms: |
#             linux/amd64
#             linux/arm64
#           file: deployments/Dockerfile
