name: Tunnel tests

on:
  push:
    paths:
      - "tunnel/**"
      - ".github/workflows/tunnel-tests.yml"
  pull_request:
    paths:
      - "tunnel/**"
      - ".github/workflows/tunnel-tests.yml"

jobs:
  test:
    name: Run Go tests for tunnel
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Show Go environment
        run: go env

      - name: Download dependencies
        working-directory: ./tunnel
        run: go mod download

      - name: Run tests
        working-directory: ./tunnel
        run: go test ./... -v
